/*
 *  Copyright (c) 2026, the Omnia developers
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

#pragma once

#include <expected>
#include <filesystem>
#include <optional>
#include <string>
#include <unordered_map>

#include <Common/Expected.h>
#include <Common/Types.h>
#include <LibAsset/Asset.h>
#include <LibAsset/Export.h>

namespace Asset {

class ASSET_API AssetSidecar final {
public:
    static constexpr std::string_view SIDECAR_EXTENSION = ".omnia";
    static constexpr std::string_view SIDECAR_HEADER = "# ! WARNING ! GENERATED BY OMNIA, DO NOT MANUALLY EDIT OR MOVE THIS FILE #\n";
    static constexpr const char* const NAME_SETTING = "name";

public:
    AssetSidecar() = default;
    AssetSidecar(AssetID id, AssetType type);

    static auto path_for(std::filesystem::path const& source_path) -> std::filesystem::path;
    static auto load(std::filesystem::path const& sidecar_path) -> Common::Expected<AssetSidecar>;

    auto save(std::filesystem::path const& sidecar_path) const -> Common::Expected<void>;

    auto id() const -> AssetID;
    auto type() const -> AssetType;

    auto setting(std::string const& key) const -> std::optional<std::string>;
    auto bool_setting(std::string const& key, bool fallback) const -> bool;
    void set_setting(std::string const& key, std::string value);

    auto hash_settings(u64 seed) const -> u64;
private:
    AssetID m_id {};
    AssetType m_type {};
    std::unordered_map<std::string, std::string> m_settings;
};

}
