add_subdirectory(Common)
add_subdirectory(LibAsset)
add_subdirectory(LibAudio)
add_subdirectory(LibConcurrency)
add_subdirectory(LibCore)
add_subdirectory(LibDebug)
add_subdirectory(LibEngine)
add_subdirectory(LibGraphics)
add_subdirectory(LibMath)
add_subdirectory(LibPhysics)
add_subdirectory(LibRenderer)
add_subdirectory(LibUI)
